OT129-49 add components news details
alkemyTech/OT129-CLIENT pull request #10
Opened 2022-01-22 02:15 UTC by AstridMata

2022-01-25 11:31 UTC, AntonyFagundez requested changes

2022-01-25 11:31 UTC, AntonyFagundez commented on src/Components/News/Details/NewsDetails.js
> +//se deja planteada para luego consumir del componente Titles
Perfecto Astrid, en líneas generales los código comentado no se sube, (comprendo que son propuestas para la ubicación del componente, pero es buena práctica no subir código comentado al PR)

2022-01-25 11:31 UTC, AntonyFagundez commented on src/Components/News/Details/NewsDetails.js
> +  )
Podríamos acá hacer ejecutar el linter para formatear un poco el código del PR

2022-01-27 20:38 UTC, AntonyFagundez commented
Hola Astrid cómo andas? por lo que veo aún hay conflictos con development! (package-lock.json) siempre porfa hagamos pull

2022-01-28 01:41 UTC, AntonyFagundez requested changes

2022-01-28 01:41 UTC, AntonyFagundez commented on src/Components/News/Details/NewsDetails.js
> +      <p>news.contenido</p>
Hola Astrid de vuelta yo, esto comprobamos que trayera la información?

2022-01-28 01:41 UTC, AntonyFagundez commented on src/Components/News/Details/NewsDetails.js
> +      <p>news.contenido</p>
Revisemos por favor el criterio de aceptación.

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-49

2022-01-28 20:03 UTC, AstridMata commented
se creo una carpeta donde se agregaran todos los componentes referidos a esta página. 

El componente se renderiza al ingresar a la ruta /novedades/:id. 

En la sección superior, debe mostrar  un título de forma dinámica, utilizando el componente para mostrar títulos. (no se ve el titulo pues aun no esta creado el componentes de títulos)

muestra imagen y contenido de la novedad de forma dinámica, se deja la ruta y condiciones ya que estos datos se obtendrán posteriormente por API. se deja planteada la petición  usando axios pero no se ejecuta.

2022-01-28 20:05 UTC, AstridMata commented on src/Components/News/Details/NewsDetails.js
> +      <p>news.contenido</p>
listo, ya lo corregí para que consuma los datos tal y como los trae la api.  cuando se haga la petición.

2022-01-29 00:39 UTC, AntonyFagundez commented
Perfecto Astrid mucho mejor, porfa separemos un poco la responsabilidades, un contenedor que haga la petición a la api como estás haciendo. Y un componente que sea solo presentacional (fijate porfa en la parte que dice titulo por props, esto es discutible si seguimos la linea de dos componentes (container llama a la API, y un componente presentacional muestra la info)

2022-01-31 02:25 UTC, FabricioCapiglioni commented
> Perfecto Astrid mucho mejor, porfa separemos un poco la responsabilidades, un contenedor que haga la petición a la api como estás haciendo. Y un componente que sea solo presentacional (fijate porfa en la parte que dice titulo por props, esto es discutible si seguimos la linea de dos componentes (container llama a la API, y un componente presentacional muestra la info)

Astrid como estas, si necesitas ayuda con esto avisame y lo vemos. Saludos.

2022-01-31 10:49 UTC, AstridMata commented
![image](https://user-images.githubusercontent.com/86080960/151780468-3867d365-70db-49eb-a4b5-88efb296f0e2.png)
se agrego una novedad con los datos seleccionados que posteriormente serán pedidos por la api 
![image](https://user-images.githubusercontent.com/86080960/151780653-4ea8d937-c611-465b-8a82-7ba24d4f0b1b.png)

2022-01-31 10:50 UTC, AstridMata commented
Hola, gracias. si me bloquee un poco pero allí estuve viendo el componente
que subió Eze, y me guié un poco pues es la misma consigna pero del
componente Activities.

El dom, 30 ene 2022 a la(s) 23:26, FabricioCapiglioni (
***@***.***) escribió:

> Perfecto Astrid mucho mejor, porfa separemos un poco la responsabilidades,
> un contenedor que haga la petición a la api como estás haciendo. Y un
> componente que sea solo presentacional (fijate porfa en la parte que dice
> titulo por props, esto es discutible si seguimos la linea de dos
> componentes (container llama a la API, y un componente presentacional
> muestra la info)
>
> Astrid como estas, si necesitas ayuda con esto avisame y lo vemos. Saludos.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT129-CLIENT/pull/10#issuecomment-1025321619>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUQX3QBXYYZCUP6DTFEVGN3UYXXMDANCNFSM5MRB5IGA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-31 15:46 UTC, AntonyFagundez approved these changes

2022-01-31 15:47 UTC, merged