[Ot129-144] Restringir acceso a formulario de login para usuario autenticado
alkemyTech/OT129-CLIENT pull request #129
Opened 2022-02-17 22:07 UTC by eze3769

# Changes:
- Added LoginPage for add Title component with LoginForm.
- Add condition to redirect to Home when user is logged.
- Correct LoginForm, which has missed an import statement.

# Ticket:
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-144&quickFilter=395

# Evidence:
![image](https://user-images.githubusercontent.com/71856261/154578215-90afa0e2-fe7f-4b8b-ac19-b374e4a10a1c.png)

2022-02-19 13:37 UTC, AntonyFagundez commented on src/Pages/LoginPage.js
> +    history.push("/");
Bueno Eze muy puntual el PR,

Ahora esta bueno este caso porque podemos encontrar las diferencias entre push y el componente Redirect.

En este caso es preferible Redirect porque si no podría romper cuando estoy loggeado y me intente devolver al home. (Porque el componente no esta devolviendo ni un elemento ni null)

Por lo que quiźa buscaría una manera de acceder al historial y devolverlo a la pagina anterior ( si existe) y/o utilizar directamente el componente `Redirect`

2022-02-19 13:37 UTC, AntonyFagundez requested changes
Con esos detalles estaríamos

2022-02-19 22:28 UTC, eze3769 commented on src/Pages/LoginPage.js
> +    history.push("/");
Cambiado el métod de history por Navigate, tanto hacia home como hacia backoffice, no incluí push para que se reemplace la ruta y no genere conflicto.

A su vez agregado isLoading en el reducer de Auth, para que se pueda ver el spinner al momento de espera y termine al ser la promesa completada o rechazada.

![image](https://user-images.githubusercontent.com/71856261/154821152-7092a9d1-8dac-4346-9ebb-f69d6334ac14.png)

2022-02-19 22:29 UTC, eze3769 commented
Agregados los cambios pedidos.

2022-02-19 23:26 UTC, AntonyFagundez requested changes
Hola Eze, ajustemos el test o el título del test porfa.

2022-02-19 23:26 UTC, AntonyFagundez commented on src/__test__/LoginForm.test.js
> +  it("Should can't summit without insert validated values on inputs", () => {
Buenísimo agregar el test de login, aunque va más allá del scope, ahora no cumple la que dice la descripción. Solo hace click en el botón.

2022-02-19 23:53 UTC, eze3769 commented on src/__test__/LoginForm.test.js
> +  it("Should can't summit without insert validated values on inputs", () => {
Perdón estuve desatento, mezclé 2 ramas, el test no iba. Lo voy a quitar de esta.

2022-02-20 13:07 UTC, eze3769 commented
Quité el archivo del test. Estuve revisando y ese archivo que tenía creado en otra rama se agregó a esta rama cuando hice el merge con development antes de pullear. De alguna forma ahí lo agregué.

2022-02-21 01:47 UTC, AntonyFagundez approved these changes
Muy bien Eze!

2022-02-21 01:48 UTC, merged