Ot129 32 formulario edicion home
alkemyTech/OT129-CLIENT pull request #13
Opened 2022-01-24 14:47 UTC by eze3769

Se agregó el componente HomeForm donde, tal como se pide en el ticket se puede editar el mensaje de bienvenida del home, se valida un mínimo de 20 caracteres con Yup, y se muestran 3 slides con texto e imágen.

Para que quede un código más limpio en HomeForm.js se creó un componenente que recibe la información de los slides como array por prop, y los muestra.

Ticket: 
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-32&quickFilter=395

Evidence:
![image](https://user-images.githubusercontent.com/71856261/150803923-80455a69-6892-43da-8493-08d4b50c4020.png)

2022-01-24 15:20 UTC, FabricioCapiglioni commented
Eze fijate que hay conflictos con el archivo app.js
![conflictos](https://user-images.githubusercontent.com/78228416/150810931-ae09424a-6bad-42f3-81a7-391a2dd8f1d1.png)

2022-01-24 17:40 UTC, eze3769 commented
Solucionado el problema de incompatibilidad para mergear en App.js

2022-01-24 20:55 UTC, AntonyFagundez commented on src/App.js
> +<<<<<<< HEAD
Hola Eze, me parece que agregaste al commit las líneas que se agregan para definir que mergear y que no.

2022-01-24 20:56 UTC, AntonyFagundez commented on src/Components/Home/HomeSlides.js
> +    })).isRequired,
Muy bien Eze, muy prolijo, lo unico, si es requerido, entonces no debería tener valor por default y viceversa.

2022-01-24 20:57 UTC, AntonyFagundez requested changes

2022-01-24 20:57 UTC, AntonyFagundez commented on src/Components/Home/HomeSlides.js
> +const HomeSlides = ({data = []}) => {
isRequired entonces con un valor por default no tendría mucho sentido.

2022-01-24 22:07 UTC, eze3769 commented on src/App.js
> +<<<<<<< HEAD
Tuve que mergear que me había quedado muy atras la branch, me quedó eso, tengo que estar más atento por lo visto

2022-01-24 22:08 UTC, eze3769 commented on src/Components/Home/HomeSlides.js
> +    })).isRequired,
Es mejor práctica alguno que otro? Ya que implementamos PropTypes uso eso para todo y quito el default?

2022-01-24 22:22 UTC, AntonyFagundez commented on src/Components/Home/HomeSlides.js
> +    })).isRequired,
No ninguno es mejor que otro, solo que si es requerido entonces no debería tener valor por default porque en teoría siempre debería 'llegar'.

2022-01-24 22:30 UTC, eze3769 commented on src/Components/Home/HomeSlides.js
> +const HomeSlides = ({data = []}) => {
Listo! Ya dejé sólo el isRequired

2022-01-24 22:31 UTC, eze3769 commented on src/App.js
> +<<<<<<< HEAD
El merge me quedó con algunos cambios pendientes, si bien los había revisado me faltó presionar para confirmar.

2022-01-25 19:37 UTC, AntonyFagundez approved these changes

2022-01-25 19:43 UTC, merged