feat: added activities deatils view with presentational and container…
alkemyTech/OT129-CLIENT pull request #15
Opened 2022-01-24 19:50 UTC by eze3769

- Creada la carpeta details dentro de Activities tal como se pide en el ticket.
- Se pide que haya un componente donde se muestren los datos de la actividad que se recibe por ID (se consigna que se traeran los datos desde la API en un futuro), el cual llamé ActivityDetailes y un componente ActivityDetailsContainer quien será el encargado de recibir el ID y traer los datos de la API.
- Si bien en entregas anteriores se creo una carpeta para contenedores, en el ticket aclara que todos deben ir en esta carpeta.
- Se utilizó PropTypes para validación de props.

Ticket:
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-50&quickFilter=395

Evidence:
![image](https://user-images.githubusercontent.com/71856261/150853159-931afeaf-fccb-429b-a719-a1003b5772fc.png)

2022-01-24 20:59 UTC, AntonyFagundez requested changes

2022-01-24 20:59 UTC, AntonyFagundez commented on src/Components/Activities/Detail/ActivitiesDetailsContainer.js
> +    <>
Hola Eze, perfecto el PR, ahora si es solo un nodo, convendría no colocar el fragment!

2022-01-24 22:02 UTC, eze3769 commented on src/Components/Activities/Detail/ActivitiesDetailsContainer.js
> +    <>
Hola, no es un sólo nodo. Para evitar problemas con los slides, y que ocupen el ancho de la web, entonces tengo un div contenedor para el h1, el slide, y luego otro contenedor con el form. No lo podría quitar, si es necesario lo puedo reemplazar por un div.

2022-01-25 18:58 UTC, eze3769 commented
Agregué los cambios que se requerían

2022-01-25 19:44 UTC, AntonyFagundez approved these changes

2022-01-25 19:45 UTC, AntonyFagundez approved these changes

2022-01-25 19:47 UTC, merged