Ot129 35 formulario creacion/edicion de miembros
alkemyTech/OT129-CLIENT pull request #16
Opened 2022-01-24 20:45 UTC by pablorosti

### Descripción 

- Se creo formulario para editar un miembro
- Se agrego dependencia de CKEditor
- Se creo una función para validar que la url sea valida

Link a ticket: https://alkemy-labs.atlassian.net/browse/OT129-35

### Evidencia
![formmember1](https://user-images.githubusercontent.com/61304153/150861605-8d96fcd1-7853-4268-8902-9c155f71ea01.png)
![editarmiembro2](https://user-images.githubusercontent.com/61304153/150861623-852d5292-1fdf-4df5-bd6b-f392d17ed969.png)

2022-01-24 21:04 UTC, AntonyFagundez requested changes

2022-01-24 21:04 UTC, AntonyFagundez commented on src/Components/Members/MembersForm.js
> +const isValidUrl = (url) => {
Está buena la función por ahí la colcaría fuera en una carpeta de utilidades para que otros puiedan usarla no te parece?

2022-01-24 21:04 UTC, AntonyFagundez commented on .eslintrc.js
> +    ecmaVersion: 12,
Hola Pablo, la versión latest no te funciona? La preferiría en tal caso.

2022-01-24 21:04 UTC, AntonyFagundez commented on .eslintrc.js
> +    "react/prop-types": "off",
Esta regla en específico no la agregaría, es una buena practica utilizar PropTypes.

2022-01-24 21:12 UTC, pablorosti commented on src/Components/Members/MembersForm.js
> +const isValidUrl = (url) => {
Si, justamente por eso agregue una carpeta utils, para que los demás puedan utilizar esta función! esta mal de esta forma?

2022-01-24 21:13 UTC, pablorosti commented on .eslintrc.js
> +    ecmaVersion: 12,
Efectivamente, no me funciona si lo dejo en latest, al igual que en mis otra branch, la única manera que me levante el proyecto es poniéndolo con la versión 12.

2022-01-24 21:25 UTC, pablorosti commented on .eslintrc.js
> +    "react/prop-types": "off",
La agregue porque tenía un problema al recibir en un componente una {children}, probé todos los tipos de definiciones para una proptype y me seguia marcando error, por eso la única solución que encontré fue agregando esa regla al eslint.js para poder seguir trabajando!

2022-01-24 21:27 UTC, pablorosti commented on src/Components/Members/MembersForm.js
> +const isValidUrl = (url) => {
Toda la razon, ahora lo soluciono!

2022-01-24 21:31 UTC, pablorosti commented on src/Components/Members/MembersForm.js
> +const isValidUrl = (url) => {
Solucionado.

2022-01-24 21:40 UTC, emquiroga commented on src/utils/isValidUrl.js
> +//Funcion para validar la url
Excelente utilidad.

2022-01-25 14:01 UTC, pablorosti commented on .eslintrc.js
> +    "react/prop-types": "off",
Solucionado

2022-01-25 19:50 UTC, AntonyFagundez approved these changes

2022-01-25 20:01 UTC, merged