Ot129 29 formulario edición creación de actividades
alkemyTech/OT129-CLIENT pull request #18
Opened 2022-01-25 03:07 UTC by FabricioCapiglioni

### Resumen

Se instalaron las dependencias Formik, CKEditor, Yup y PropTypes.

El formulario admite creación de actividades y edición en caso de recibir id el objeto recibido por props.

Se utilizan 2 funciones asincronas tanto para crear como para editar una actividad y enviarla al endpoint según corresponda.

Se creo el componente ActivityFormContainer.

### Evidencia

![Create Activity](https://user-images.githubusercontent.com/78228416/150903404-9a4a6486-c540-424d-81b7-56a70e8cffc0.png)
![Edit Activity](https://user-images.githubusercontent.com/78228416/150903406-09128413-1c3a-4bb5-b7d5-bb29e4d581c7.png)
![validation](https://user-images.githubusercontent.com/78228416/150903408-156f0555-240b-4c9d-992d-99e2e34fbbaa.png)

2022-01-25 20:20 UTC, AntonyFagundez requested changes

2022-01-25 20:20 UTC, AntonyFagundez commented on src/Components/Activities/ActivitiesForm.js
> +const toBase64 = async (file) =>
Siempre que tengamos utilidades de este tipo, coloquemoslas por fuera para su reutilización

2022-01-25 20:20 UTC, AntonyFagundez commented on src/Components/Activities/ActivitiesForm.js
> +};
En este caso no convendría hacerlo en otro archivo?

2022-01-25 20:20 UTC, AntonyFagundez commented on src/Containers/Activities/ActivitiesFormContainer.js
> +  /* const {id} = useParams() */
Evitemos dejar código comentado, comprendo que esto era para usar en un futuro cuando se necesitara, pero es más pulcro solo subir código referido al scope y al PR

2022-01-25 23:33 UTC, FabricioCapiglioni commented on src/Containers/Activities/ActivitiesFormContainer.js
> +  /* const {id} = useParams() */
Hola Antony, sí despues de haberlo subido me di cuenta que no debía. Elimino el archivo y hacemos el componente más adelante.

2022-01-26 02:48 UTC, FabricioCapiglioni commented on src/Components/Activities/ActivitiesForm.js
> +const toBase64 = async (file) =>
Antony, ahí traje development y Pablo hizo la misma función en la carpeta utilities, por lo que itilizo la misma

2022-01-26 12:54 UTC, AntonyFagundez commented on src/Services/create.js
> +/* eslint-disable no-console */
Preferiría evitar el eslint-disable a menos que sea estrictamente necesaria

2022-01-26 12:55 UTC, AntonyFagundez approved these changes
Faltar

2022-01-26 13:01 UTC, merged