OT129 34 formulario de actualizacion
alkemyTech/OT129-CLIENT pull request #19
Opened 2022-01-25 17:08 UTC by emquiroga

**DESCRIPTION:** 

- Added form component for organization info edit.
- Added form container with mockups data.
- Added CKEditor to dependencies.
- Validated all fields.

**TICKET:** 

- https://alkemy-labs.atlassian.net/browse/OT129-34

EVIDENCE:

![image](https://user-images.githubusercontent.com/82418581/151024644-f0196ac1-4cec-40a9-8463-607f1da1a4c5.png)

2022-01-25 20:26 UTC, AntonyFagundez requested changes

2022-01-25 20:26 UTC, AntonyFagundez commented on src/Components/EditForm/EditForm.js
> +import "bootstrap/dist/css/bootstrap.css";
Hola Emi, Por lo general esto solo se importa en app, con una vez basta!

2022-01-25 20:26 UTC, AntonyFagundez commented on src/Components/EditForm/EditForm.js
> +  };
Si el objeto data es exactamente al objeto initialvalues, no convendría no declararlo y repetir propiedad por propiedad,

en tal caso: `initialValues={data}`

2022-01-25 20:28 UTC, emquiroga commented on src/Components/EditForm/EditForm.js
> +import "bootstrap/dist/css/bootstrap.css";
Oki, ahora lo vuelo.

2022-01-25 20:43 UTC, emquiroga commented on src/Components/EditForm/EditForm.js
> +  };
Excelente, ahora lo arreglo.

2022-01-25 20:52 UTC, emquiroga commented
Hechos los cambios y el pull desde dev.

2022-01-26 13:03 UTC, AntonyFagundez approved these changes

2022-01-26 13:05 UTC, merged