[OT129 28] Formulario de creación y edición de categorías
alkemyTech/OT129-CLIENT pull request #20
Opened 2022-01-26 12:38 UTC by anagalli

Formulario para la creación y edición de categorías. En el caso de no recibir un objeto de categoría existente, mostrar los campos vacíos y realizar una petición POST al endpoint de creación de categorías (/categories). En el caso de recibirla, completar el formulario con los campos de la misma y realizar una petición PATCH al endpoint de actualización del server (/categories/:id).

- Todos los campo son obligatorios
- Name debe contener una longitud mínima de 4 caracteres
- La imagen deberá tener un formato .jpg o .png

2022-01-26 13:14 UTC, AntonyFagundez requested changes

2022-01-26 13:14 UTC, AntonyFagundez commented on src/Containers/Categories/CategoriesContainer.js
> +  });
Hola Ana como va? Está utilidad ya está en utils, podrías exportarla, y en tal caso si no existiera y ves que es reutilizable siempre esta bueno disponibilizarlo para todos!

2022-01-26 13:14 UTC, AntonyFagundez commented on src/Containers/Categories/CategoriesContainer.js
> +};
En lo general estas funciones siempre irían afuera, para dejar que el archivo solo tenga información relacionada al componente

2022-01-27 00:29 UTC, anagalli commented on src/Containers/Categories/CategoriesContainer.js
> +  });
Realizada la importación de la función para reutilizarla.

2022-01-27 00:29 UTC, anagalli commented on src/Containers/Categories/CategoriesContainer.js
> +};
Reutilicé dos funciones para edit y create que estaban en la carpeta Services.

2022-01-27 01:30 UTC, AntonyFagundez commented on src/Components/Categories/CategoriesForm.js
> +    values.id === undefined ? create("categories", data) : edit("categories", data);
Muy bien! bastante pulcro.

2022-01-27 01:31 UTC, AntonyFagundez approved these changes

2022-01-27 01:33 UTC, merged