Ot129 61 screen listado de novedades backoffice
alkemyTech/OT129-CLIENT pull request #23
Opened 2022-01-26 20:10 UTC by pablorosti

### DESCRIPCIÓN

- Se creo ruta contenedora de componentes de novedades
- Se agrego componente tabla para mostrar todas las novedades con sus respectivos botones de edición y eliminación además de botón para crear una novedad que redirige a la pagina para crear una novedad
- Se agrego dependencia DATE-FNS para formatear fechas

### LINK
https://alkemy-labs.atlassian.net/browse/OT129-61

### EVIDENCIA
![NOVEDADES1](https://user-images.githubusercontent.com/61304153/151238881-c1968de9-22b1-4e40-9e60-822a5f763ed6.png)

2022-01-27 01:41 UTC, AntonyFagundez requested changes

2022-01-27 01:41 UTC, AntonyFagundez commented on src/App.js
> +import NewsForm from "./Components/News/NewsForm.jsx";
Hola Pablo, esto está por alguna razón, por lo general no se acostumbra a colocar la extensión del archivo

2022-01-27 01:42 UTC, AntonyFagundez commented on public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
Consulta esto lo agregamos debido a?

2022-01-27 11:15 UTC, pablorosti commented on src/App.js
> +import NewsForm from "./Components/News/NewsForm.jsx";
Raro eso, cuando cambie la extensión del archivo, VSC me pidió si quería cambiar las importaciones, me lo debe haber cambiado ahí porque nunca lo agregue a eso, ahora lo quito :)

2022-01-27 11:16 UTC, pablorosti commented on public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
Ese cdn lo agregué para el uso de los iconos de fontawesome

2022-01-27 11:29 UTC, AntonyFagundez approved these changes

2022-01-28 01:24 UTC, AntonyFagundez approved these changes

2022-01-28 01:26 UTC, merged