Ot129 53 slider
alkemyTech/OT129-CLIENT pull request #25
Opened 2022-01-27 14:06 UTC by emquiroga

**DESCRIPTION:**

- Added HomePage to App.js.
- Created HomeSlide container with API get service
- Modified HomeSlides component for home reutilization.

**TICKET:**
- https://alkemy-labs.atlassian.net/browse/OT129-53

**EVIDENCE:**

![Screenshot 2022-01-27 at 10-56-02 React Redux App](https://user-images.githubusercontent.com/82418581/151374091-e42a33df-51c6-4137-807a-dfa39f2a044b.png)
![Screenshot 2022-01-27 at 11-03-12 React Redux App](https://user-images.githubusercontent.com/82418581/151374097-947ed497-01b9-4e06-ba0c-10611507fe30.png)
![Screenshot 2022-01-27 at 11-03-26 React Redux App](https://user-images.githubusercontent.com/82418581/151374101-d802a9cd-1f3e-405e-acfa-8d354bef7209.png)
![Screenshot 2022-01-27 at 11-03-36 React Redux App](https://user-images.githubusercontent.com/82418581/151374103-bcdaff0d-6c74-490f-a797-d48c7c7a2ddf.png)
![Screenshot 2022-01-27 at 11-03-52 React Redux App](https://user-images.githubusercontent.com/82418581/151374105-adf0b713-8b42-4769-a4e8-38c4452f4e53.png)

**Sugested changes (out of ticket scope):**

- Set up an standard height property.
- Box shadow for text containers.
- Background for buttons visibility.

2022-01-27 20:44 UTC, AntonyFagundez requested changes

2022-01-27 20:44 UTC, AntonyFagundez commented on src/Components/Home/HomeSlides.js
> +              key={el.id ?? index}
si colocamos un index como default por si el id no está porfa hagamos un index un poco más complejo tipo: ``CarouselItem-${index}`` , debido a que si todos solo colocamos un index va a aparecer un problema en la consola

2022-01-27 20:44 UTC, AntonyFagundez commented on src/Containers/HomeSlide/HomeSlide.js
> +const axios = require("axios");
cuidado con la mezcla de imports.

2022-01-27 21:15 UTC, emquiroga commented on src/Containers/HomeSlide/HomeSlide.js
> +const axios = require("axios");
Sí, fue una autocorreción por el require en lugar del import. Fixed.

2022-01-27 21:16 UTC, emquiroga commented on src/Components/Home/HomeSlides.js
> +              key={el.id ?? index}
Cierto, fixed.

2022-01-28 01:46 UTC, AntonyFagundez approved these changes

2022-01-28 01:46 UTC, merged