OT129-65 screen listado usuarios
alkemyTech/OT129-CLIENT pull request #32
Opened 2022-01-28 20:08 UTC by malks14

En esta rama, lo que se realizo fue la tabla para que el administrador pueda ver el nombre y el email de los usuarios.

A su vez, se agregaron botones funcionales de editar, eliminar, cancelar y aceptar a la edicion de usuarios.

Tambien, lo que se agrego por CDN fue fontawesome para los botones de la tabla.

Por ultimo. se agrego un boton de crear usuario, que el mismo lleva a la ruta solicitada "/backoffice/users/create"

### Evidencias: 
<img width="498" alt="Screen Shot 2022-01-28 at 17 07 48" src="https://user-images.githubusercontent.com/73920001/151614386-af6ad301-b3aa-49ce-be29-c6082e269598.png">

<img width="682" alt="Screen Shot 2022-01-28 at 17 08 21" src="https://user-images.githubusercontent.com/73920001/151614440-d59cbcb7-3e33-44d4-bc61-63d29442111a.png">

2022-01-28 21:15 UTC, emquiroga commented on .eslintrc.js
> +    ecmaVersion: 12,
Esto debería estar en "latest" para hacer un merge, que es como todos la estamos usando.

2022-01-29 01:27 UTC, AntonyFagundez requested changes
Hola Guido cómo va? un poco viendo el ticket y los requerimientos, (como lo charlamos previamente) debemos utilizar el editar usuario que ya estaba creado.

2022-01-29 01:27 UTC, AntonyFagundez commented on src/Components/Back/BackUsersList.js
> +import "bootstrap/dist/css/bootstrap.css";
Hola Guido como andas, muy buen PR; este import debería estar solo en app o index

2022-01-31 15:20 UTC, AntonyFagundez commented on src/Pages/BackOfficeUserPage.js
> +  const linkUrl = "/backoffice/users/create";
Muy bien el PR unico comentario no bloqueante: 
constantes siempre en mayusculas LINK_URL, y si es como este caso que vos sabes que es una constante afuera del componente, así no se evalua siempre en cada render.

2022-01-31 15:20 UTC, AntonyFagundez approved these changes

2022-01-31 15:20 UTC, AntonyFagundez commented
Hola Guido último detalle con respecto a la tarea y la descripcion:
 En la sección superior, mostrará un componente <Link> que redirigirá a la ruta /backoffice/users/create.

En toda la tabla debería haber

2022-01-31 15:20 UTC, merged