Ot129 67 listado de miembros de la organizacion pagina nosotros
alkemyTech/OT129-CLIENT pull request #34
Opened 2022-01-28 23:29 UTC by FabricioCapiglioni

### **Summary**

Add component MemersList that receives an array of objects and map them.

Add component Member Card that receives an object and show data in a card presentation

### **Evidence**
![Members list](https://user-images.githubusercontent.com/78228416/151635217-3afeb28e-f97d-4db3-8828-e8c70e08c0dc.jpg)

2022-01-28 23:47 UTC, anagalli commented on src/Components/About/MemberCard.css
> +    box-shadow: var(--card-shadow);
Quedaron re bien las cards! Detalle opcional que sumaría al css, acomodar las imágenes para que no se deformen al adaptarse al contenedor. Puede ser con un object fit cover por ejemplo. Pero como detalle fino nada más.

2022-01-29 01:32 UTC, AntonyFagundez commented on src/Components/About/MemberCard.css
> +    box-shadow: var(--card-shadow);
Excelente, muy buena recomendación!

2022-01-29 01:34 UTC, AntonyFagundez requested changes
Solo son detalles puntuales

2022-01-29 01:34 UTC, AntonyFagundez commented on src/Components/About/MemberCard.js
> +import React from "react";
Porfa linteemos todos los archivos

2022-01-30 14:56 UTC, AntonyFagundez approved these changes

2022-01-31 02:03 UTC, FabricioCapiglioni commented on src/Components/About/MemberCard.css
> +    box-shadow: var(--card-shadow);
Quedó muy bien, y con esa recomendación quedó mejor aún, muchas gracias Ana. Les adjunto una captura con la modificación comentada.
![members](https://user-images.githubusercontent.com/78228416/151729437-7869d6d8-bc94-4a5a-bd69-0b29c9e1da16.jpg)

2022-01-31 02:04 UTC, merged