Ot129 60 crear card component
alkemyTech/OT129-CLIENT pull request #35
Opened 2022-01-30 21:54 UTC by ivanedusalas

-**default image in placeholder
-cards order in column/row**
-**reusable component for the different sections
-receives information from the page that uses it, for example activities and news**

![image](https://user-images.githubusercontent.com/91094245/151719221-5a5f6fbb-fddf-4a5d-ba33-a81a4fd57499.png)

2022-01-31 15:31 UTC, AntonyFagundez requested changes

2022-01-31 15:31 UTC, AntonyFagundez commented on src/Containers/CardContainer/ContainerCard.js
> +          <div key={index} className="col">
Hola Ivan muy pulcro el PR, buena practica, nunca se utiliza index puro como key (¿Cuantos elementos no tendrían index 0,1,2,3?) Siempre optemos por un key más complejo como ``ShowCard-Container-${1}`` o algo por el estilo.

2022-01-31 15:31 UTC, AntonyFagundez commented on src/Containers/CardContainer/ContainerCard.js
> +            <ShowCard description={el.description} image={el.image} title={el.name} />
Si el objeto tiene las mismas propiedades que el componente podría ser así:
`<ShowCard {...el} />`o si es como este caso que solo cambia name/title podríamos desttructurar el elemento y obtener las propiedades iguales:
``` jsx
map(({ name, similarProps }, index) => <ShowCard title={name}  {...similarProps} />
```

2022-01-31 15:31 UTC, AntonyFagundez commented on .eslintrc.js
> +    ecmaVersion: 12,
Porfa dejemos la versión latest

2022-01-31 16:00 UTC, ivanedusalas commented on .eslintrc.js
> +    ecmaVersion: 12,
commitié por error esas lineas, ahora lo corrijo.

2022-01-31 16:25 UTC, ivanedusalas commented on src/Containers/CardContainer/ContainerCard.js
> +            <ShowCard description={el.description} image={el.image} title={el.name} />
El mock realizado es diferente al objeto que llega de la API, por lo tanto debo traer solo esos atributos mencionados antony

2022-01-31 16:28 UTC, ivanedusalas commented on src/Containers/CardContainer/ContainerCard.js
> +          <div key={index} className="col">
Removí el index como parametro, y utilicé como key el id del objeto mapeado.

2022-02-01 13:01 UTC, AntonyFagundez approved these changes

2022-02-01 13:02 UTC, merged