Ot129 30 formulario edición  creación de slides
alkemyTech/OT129-CLIENT pull request #36
Opened 2022-01-31 00:37 UTC by AstridMata

Validaciones:
Todos los campos son obligatorios
Name debe tener una longitud mínima de 4 caracteres 
Órder debe ser único
La imagen deberá tener un formato .jpg o .png

![image](https://user-images.githubusercontent.com/86080960/151724683-d7d371f8-0699-4c68-820b-a7bf02619830.png)

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-30&quickFilter=395

2022-01-31 15:45 UTC, AntonyFagundez requested changes

2022-01-31 15:45 UTC, AntonyFagundez commented on src/Components/Slides/SlidesForm.js
> +          });
Hola strid muy pulcro el PR, bastante puntual, me llama la atención que id sea true, esto está bien?
Recordemos que en js podes asignarles propeidades al objeto de esta forma
``` js
setInitialValues({
            name
            description,
            order,
            image,
            // ...
          });
```

Ahora bien recordemos que si order es 0 lo va a entender como falsy, aparte order es obligatorio

2022-01-31 15:45 UTC, AntonyFagundez commented on src/Components/Slides/SlidesForm.js
> +  }, []); // eslint-disable-line
Porfa si tenemos ESLINT como herramienta de trabajo, no logramos nada desactivando, prestemosle atención a los warnings y resolvamos las advertencias. En este caso supongo que estaría pidiendo las funciones en el array de dependencias.

2022-01-31 15:45 UTC, AntonyFagundez commented on src/Components/Slides/SlidesForm.js
> +            enableReinitialize={true}
Todo flag en React que queramos colocar como true basta escribirlo no más, es decir,

``` jsx
<Formik enableReinitialize={true} 
//ignorado para reducir ejemplo
/>
```

es lo mismo que

``` jsx
<Formik enableReinitialize
//ignorado para reducir ejemplo
/>
```

2022-01-31 15:52 UTC, AstridMata commented on src/Components/Slides/SlidesForm.js
> +            enableReinitialize={true}
ok entiendo ahora lo corrijo. gracias

2022-02-01 13:04 UTC, AntonyFagundez approved these changes

2022-02-01 13:07 UTC, merged