Ot129 55 crear componente para renderizar sección contacto con los datos de contacto de la ong
alkemyTech/OT129-CLIENT pull request #37
Opened 2022-01-31 13:33 UTC by pablorosti

### Descripción

- Se agrego componente para mostrar página de contactos reutilizando componente Título

### Link
https://alkemy-labs.atlassian.net/browse/OT129-55

### Evidencia
![contactPage](https://user-images.githubusercontent.com/61304153/151802719-e5a9dcc5-02fb-4346-9c08-65f42f27e166.png)

2022-01-31 15:51 UTC, AntonyFagundez requested changes

2022-01-31 15:51 UTC, AntonyFagundez commented on package.json
> +    "@ckeditor/ckeditor5-build-classic": "^31.1.0",
Perfecto Pablo, muy puntual y pulcro el PR, unico detalle, no utilicemos el ^ en las versiones para evitar conflicto porfa!

2022-01-31 23:04 UTC, pablorosti commented on package.json
> +    "@ckeditor/ckeditor5-build-classic": "^31.1.0",
Solucionado!

2022-02-01 13:28 UTC, AntonyFagundez approved these changes

2022-02-01 13:30 UTC, merged