[OT129-122] Integrar eslint
alkemyTech/OT129-CLIENT pull request #4
Opened 2022-01-20 16:27 UTC by pablorosti

## SUMARY:

- Added eslint
- The following added dependencies: bootstrap, axios, formik, yup

## Evidence
![evidencia eslint](https://user-images.githubusercontent.com/61304153/150379605-545e9631-1ec8-453a-9abd-2fd9737b816e.png)
![evidence2](https://user-images.githubusercontent.com/61304153/150379798-854e755a-398f-4ffb-b066-486d6d376a2c.png)
![evidence3](https://user-images.githubusercontent.com/61304153/150380030-d811a31b-571a-46d4-ace3-849ba919a5c9.png)

2022-01-20 17:42 UTC, AntonyFagundez requested changes
Por lo que veo está bien lo único es que no se ha aplicado los fixes del lint a todo el proyecto, porfavor investigar:
https://eslint.org/docs/user-guide/command-line-interface.

Y agregarlo al package json como un script para que quede automatico para todos:

package.json
``` json
  //...resto de package.json
 "scripts": {
    "lint": //linea de comandos que ejecuta eslint
    "lint:fix" //linea de comandos que ejecuta eslint y arregla automaticamente
  }
  
```

2022-01-20 21:05 UTC, AntonyFagundez commented on .eslintrc.js
> +    node: true,
Probaron los test, juraría que falta en env de jest

2022-01-20 21:08 UTC, AntonyFagundez requested changes

2022-01-20 21:08 UTC, AntonyFagundez commented on src/Campaigns/Toys/Slider.js
>  import React from 'react';
Las comillas deben estar uniformes, hay archivos con comillas simples y otros con comillas dobles. Revisar

2022-01-21 12:13 UTC, pablorosti commented on src/Campaigns/Toys/Slider.js
>  import React from 'react';
Resuelto.

2022-01-21 15:35 UTC, AntonyFagundez approved these changes

2022-01-21 17:44 UTC, merged