Update styles of tables backoffice
alkemyTech/OT129-CLIENT pull request #48
Opened 2022-02-01 19:59 UTC by anagalli

- General styles file (index.css)  updated with backoffice tables styles.
- Backoffice tables styles updated (Users, Categories, Slides, Members, News and Activities).

![total-view-tables-styles](https://user-images.githubusercontent.com/97997049/152041858-d522a185-b539-493c-af7a-8467182d4c90.jpg)

2022-02-01 22:49 UTC, AntonyFagundez commented
Perfecto, muy especifico y bien el PR.

Ahora aprovechemos ya que estamos, y estandarizemos el tema del id, o todos lo tienen o ninguno lo tiene (yo optaría por mostrarlo), por otra parte las imagenes estandaricemos el tamaño para que no sea tan dispar entre tablas. porfa!

2022-02-01 22:50 UTC, AntonyFagundez requested changes
Con esos detalles de estandarización estaríamos!

2022-02-02 15:17 UTC, anagalli commented
Todos los id de las tablas fueron agregados. 
Las imágenes ya tenían un tamaño estandarizado de 150x150, en las fotos de las evidencias se ve diferente. 
Se acomodaron rutas de los botones de crear de algunas tablas que se diferenciaban de lo especificado en el ticket para que se visualicen correctamente los componentes de formulario a los que redirigen.

2022-02-04 00:55 UTC, AntonyFagundez commented
Hola Ana muy bien, te pido porfa que me ayudes a revisar el merge y las rutas, las organicé con respecto a lo que son, habría que estandarizar un poco algunas, y revisar especificamente cual es el container de Activities que no me queda claro.

2022-02-05 00:33 UTC, AntonyFagundez approved these changes

2022-02-05 00:33 UTC, merged