delete request in private services created
alkemyTech/OT129-CLIENT pull request #56
Opened 2022-02-02 17:22 UTC by ivanedusalas

-**Feat: delete request in private services created**

![image](https://user-images.githubusercontent.com/91094245/152203923-fc0cd77c-6834-4ce7-894a-1c73693e28fa.png)

2022-02-02 23:49 UTC, AntonyFagundez requested changes

2022-02-02 23:49 UTC, AntonyFagundez commented on src/Services/privateApiService.js
> +export const del = (url, id) => instance.delete(`${url}/${id}`);
Perfecto el PR, puntual y está bien, ahora con respecto a buenas practicas `del` no es descriptivo, supongo que tuviste problema porque `delete` es una palabra reservada en js, recomiendo cambiarla por `remove`

2022-02-03 00:27 UTC, ivanedusalas reviewed
--**function name change for a better description**

![image](https://user-images.githubusercontent.com/91094245/152260490-2aa9b13c-a00a-4bde-ab4b-794850e7925d.png)

![image](https://user-images.githubusercontent.com/91094245/152260449-b7dbc1a2-13a7-43a0-80c7-ab4cea6475c9.png)

2022-02-03 00:53 UTC, AntonyFagundez approved these changes

2022-02-03 00:53 UTC, merged