Ot129 39 screen datos de organizacion backoffice
alkemyTech/OT129-CLIENT pull request #6
Opened 2022-01-20 19:06 UTC by eze3769

Corrected components structure: created OrganizationContainer and includes mockup data inside that container.
Corrected bootstrap dependecies. React-bootstrap removed.
Corrected routes for those components.

2022-01-20 21:02 UTC, AntonyFagundez requested changes

2022-01-20 22:38 UTC, eze3769 commented on src/Containers/Organization/OrganizationContainer.js
> +    //datos mockups hasta armar la estructura definitiva
moví la declaración de la constante fuera de la función que define el componente y le cambié el nombre a organizationData.

2022-01-20 23:01 UTC, eze3769 commented on src/Components/Organization/Organization.js
> +const Organization = ({organizationMock}) => {
Le cambie el nombre a organizationData, no se si en este caso hay una convención que estoy pasando por alto para nombres. PropTypes no había usado, lo apliqué, y también deje un valor por defecto para que en caso de no recibir la prop a lo sumo no se rompa la app. Al mismo tiempo agregué un spinner y condicionales en caso de que algún dato no esté disponible, o que por asincronía demore la carga de la información.

2022-01-21 13:22 UTC, eze3769 commented on src/Components/Organization/Organization.js
> +const Organization = ({organizationMock}) => {
Quité lo extra

2022-01-21 15:31 UTC, AntonyFagundez commented on src/Components/Organization/Organization.js
> +const Organization = ({organizationData}) => {
Perfecto, último detalle. Si el componente se llama Organization, la propiedad data se sobreentiende que es de la organización, por lo tanto queda redudante que el componente Organization tenga una propiedad llamada organizationData, bastaría con `data`

2022-01-21 15:32 UTC, AntonyFagundez requested changes

2022-01-21 15:33 UTC, AntonyFagundez commented on src/Components/Organization/Organization.js
> +const Organization = ({organizationMock}) => {
Perfecto lo de PropTypes, exactamente se debe hacer así, te agregué un comentario aparte acerca de la propiedad organizationData.

2022-01-21 21:29 UTC, AntonyFagundez approved these changes

2022-01-22 23:47 UTC, merged