[Ot129 91] crear variables de entorno (organization)
alkemyTech/OT129-CLIENT pull request #73
Opened 2022-02-04 17:28 UTC by eze3769

- Added Organization endpoint in .env.example
- Created organizationServices in services.
- Refactor organizationContainer, replacing mockup data with an API call.

Ticket:
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-91&quickFilter=395

Evidence: 

![image](https://user-images.githubusercontent.com/71856261/152574818-8b9e5a7a-3a4b-40a6-ad86-546fdeddd8f5.png)
![image](https://user-images.githubusercontent.com/71856261/152574885-18289ff4-5422-4f74-8460-2a5ec8df74dc.png)
![image](https://user-images.githubusercontent.com/71856261/152575007-3305df89-9806-42bb-b160-8b15b140515d.png)

2022-02-05 01:34 UTC, AntonyFagundez requested changes

2022-02-05 01:34 UTC, AntonyFagundez commented on src/Services/organizationService.js
> +};
Hola Eze, muy puntual el PR, add or Edit son metodos que deberían recibir argumentos.

2022-02-07 12:36 UTC, eze3769 commented
Corrected add and edit params, adding id and data as it matches.

2022-02-07 21:35 UTC, AntonyFagundez approved these changes
Perfecto ultimo detalle a revisar en proximos pr, al usar axios no es necesario el `res.json()`

2022-02-07 21:36 UTC, merged