[Ot129 102] mostrar errores cuando las peticiones no se realicen correctamente
alkemyTech/OT129-CLIENT pull request #74
Opened 2022-02-04 20:46 UTC by eze3769

- Added Interceptors for handle error on server responses.

! I have some issues because add commits in a wrong branch, for that question i have to reset some commits and move into this branch.

Ticket:
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT129/boards/196?modal=detail&selectedIssue=OT129-102&quickFilter=395

Evidence:
![image](https://user-images.githubusercontent.com/71856261/152600502-a9bca0e3-fa26-4d71-bbdd-7e348125df2c.png)

2022-02-05 01:40 UTC, AntonyFagundez requested changes

2022-02-05 01:40 UTC, AntonyFagundez commented on src/Services/privateApiService.js
> +    alerts(error, "error");
Perfecto buen uso de los interceptores, justo lo que haríamos, porfa acordemos un mensaje un poco más amigable para el usuario. (_error_ no es muy amigable)

2022-02-05 01:40 UTC, AntonyFagundez commented on src/Services/organizationService.js
> +};
Mismo comentario del anterior, revisemos porfa los argumentos de add y de edit

2022-02-05 03:55 UTC, FabricioCapiglioni commented on src/Services/privateApiService.js
> +    alerts(error, "error");
Buenas como están, vi que se podría interceptar el código de respuesta HTTP y según el código poder darle un mensaje más preciso del error, no se si aplicaría para este caso.

2022-02-07 12:50 UTC, eze3769 commented on src/Services/privateApiService.js
> +    alerts(error, "error");
Hola Antony, cómo va?
Corregí el mensaje, de todas formas eso "error" corresponde a la selección del ícono en SweetAlerts, lo que mostraba era el mensaje que enviaba el servidor. Tampoco era muy amigable, así que lo reemplace por "No hemos podido recuperar la información. Por favor intente nuevamente a la brevedad."

No creo que haya que especificar tanto ya que el usuario no necesita saber nada técnico ni manejar el error. No se si hacer un mensaje más amistoso, como por ejemplo, "UPS! Algo no funcionó, intente más tarde", o algo por el estilo

2022-02-07 12:54 UTC, eze3769 commented
Error message change from server error message to "No hemos podido recuperar la información. Por favor intente a la brevedad"

Evidence:
![image](https://user-images.githubusercontent.com/71856261/152791853-b1dfa6af-c3d4-48da-a27f-807d50d1eb90.png)

2022-02-08 00:27 UTC, AntonyFagundez approved these changes

2022-02-08 00:30 UTC, merged