[OT129-36] Crear componente de formulario de Contacto
alkemyTech/OT129-CLIENT pull request #8
Opened 2022-01-20 23:04 UTC by anagalli

I created a new folder in components for the contact form component and added the form with its validations. 

- The inputs must be name, email, phone and message. All required. 
- The email format must be verified. 
- The phone number must have a minimum of 8 digits.

2022-01-21 17:56 UTC, AntonyFagundez requested changes

2022-01-21 17:56 UTC, AntonyFagundez commented on src/Components/Contact/ContactForm.js
> +    }
Hola Ana cómo va? 
Casos como constantes, que no corresponden directamente al componente, deberían estar fuera del mismo para evitar evaluarse en cada render

2022-01-21 17:56 UTC, AntonyFagundez commented on src/Components/Contact/ContactForm.js
> +    });
Mismo caso que el anterior

2022-01-25 11:19 UTC, AntonyFagundez requested changes

2022-01-25 11:19 UTC, AntonyFagundez commented on src/Components/Contact/ContactForm.js
> +});
Hola Ana cómo estás? Muy bien el PR, muy prolijo todo, ahora, en este caso necesitaría que todo el código que subas esté formateado con ESlint (npm run lint:fix) para que todo esté ordenado.

2022-01-25 11:19 UTC, AntonyFagundez commented on .eslintrc.js
> +    ecmaVersion: 12,
Este cambio a que se debe? A algo en específico?

2022-01-25 12:59 UTC, anagalli commented on src/Components/Contact/ContactForm.js
> +});
Hola Antony! Lo había ejecutado al comando. No sé que es lo que quedó mal, para revisarlo. Recién lo ejecuté nuevamente y no me marca ningun error, sólo los warnings de los console.log que hay en varios archivos.

2022-01-25 16:43 UTC, AntonyFagundez approved these changes

2022-01-25 19:18 UTC, merged