Ot129 76 Extender servicio http novedades
alkemyTech/OT129-CLIENT pull request #81
Opened 2022-02-07 16:34 UTC by ivanedusalas

Feat:
-  Container for news list
-  HTTP requests for news components created and updated

Fix: 
- Mocks in News components removed
- Header in AxiosConfig needs to be configured to make public requests
***

### EVIDENCE
- **GET ALL**
![image](https://user-images.githubusercontent.com/91094245/152827981-137138b6-bbaa-444a-9eca-985482b57dae.png)
- **GET BY ID**
![image](https://user-images.githubusercontent.com/91094245/152828435-fd84f35b-5eca-44e0-a377-dbdc24ecba63.png)
- **POST**
![image](https://user-images.githubusercontent.com/91094245/152830182-4d057118-667b-4017-afa6-dd860d56312a.png)
- **PUT**
![image](https://user-images.githubusercontent.com/91094245/152829241-075e6298-ceb3-4971-8333-fe7a8f148956.png)
- **DELETE**
![image](https://user-images.githubusercontent.com/91094245/152830505-39c6d14a-a8d7-44b7-a52b-68ccc7fff997.png)

2022-02-07 22:37 UTC, pablorosti submitted a review, later dismissed

2022-02-07 22:37 UTC, pablorosti commented on src/Components/News/NewsForm.jsx
> +    console.log(initialValues);
Hola Iván espero ya te encuentres mejor!
No sería conveniente eliminar este console.log?

2022-02-07 22:37 UTC, pablorosti commented on src/Containers/News/NewsContainer.js
> +      console.log(id);
Lo mismo que el comentario de arriba

2022-02-07 22:44 UTC, ivanedusalas commented on src/Components/News/NewsTableRow.jsx
> +          onClick={() => removeNews(data.id)}
Hola pablo, pensé lo mismo que vos! pero hay un ticket aparte que exige eso, y no debía irme del scope.

2022-02-07 22:59 UTC, ivanedusalas commented on src/Containers/News/NewsContainer.js
> +      console.log(id);
gracias por la revision pablo!

2022-02-07 23:00 UTC, ivanedusalas commented on src/Containers/News/NewsContainer.js
> +        .catch((err) => console.log(err));
quedaron en un commit previo evidentemente, gracias pablo!

2022-02-07 23:00 UTC, ivanedusalas commented on src/Components/News/NewsForm.jsx
> +    console.log(initialValues);
si, quedaron en un commit anterior, gracias pablo!

2022-02-08 01:02 UTC, AntonyFagundez requested changes

2022-02-08 01:02 UTC, AntonyFagundez commented on src/Services/axiosConfig.js
> -    Group: "129",
Hola Ivan cómo estás? Hay que revisar que estamos haciendo bien/mal para no eliminar el grupo de tooodos los request. Porfa no cambiemos esto a menos que sea estrictamente necesario

2022-02-08 22:54 UTC, AntonyFagundez approved these changes

2022-02-08 22:57 UTC, AntonyFagundez approved these changes

2022-02-08 23:00 UTC, merged