Ot129 26 formulario login
alkemyTech/OT129-CLIENT pull request #9
Opened 2022-01-21 02:44 UTC by ivanedusalas

- **Se Modificó el componente LoginForm**
-**Utilización de Formik para formulario y Yup para validaciones del mismo**
- **Ruteo en app.js para visualizar el componente**
- **Se crea una función que recibe los campos completados, los aloja en una constante  y realiza la petición http mediante axios**

2022-01-21 13:43 UTC, eze3769 commented
Te conviene pullear primero los cambios en la rama developer, para evitar esos conflictos.

2022-01-21 17:54 UTC, AntonyFagundez requested changes

2022-01-21 17:54 UTC, AntonyFagundez commented on src/Components/Auth/LoginForm.js
> +  const startValues = {
Hola Ivan buenas cómo andas? Constantes y valores que puedan vivir fuera del componente siempre afuera.

2022-01-22 02:28 UTC, ivanedusalas commented on src/Components/Auth/LoginForm.js
> +  const startValues = {
Bien ahora lo modifico, gracias

2022-01-22 13:38 UTC, ivanedusalas commented on src/Components/Auth/LoginForm.js
> +      validationSchema={Yup.object().shape({
Perfecto gracias antony

2022-01-24 20:51 UTC, AntonyFagundez commented on .eslintrc.js
> +=======
Hola Ivan, me parece que por error agregaste lo que genera git al intentar hacer merge entre archivos:
```
<<<<<<< HEAD
=======
>>>>>>> 2ef509bde12f3834ad27713c285679a1ef8b6c7e
```

2022-01-24 22:55 UTC, ivanedusalas commented on .eslintrc.js
> +=======
Gracias Antony, solucionado

2022-01-26 13:15 UTC, AntonyFagundez commented on .eslintrc.js
> +    ecmaVersion: 12,
Hola Ivan, esto debería ser version latest como en development!

2022-01-26 14:12 UTC, ivanedusalas commented on .eslintrc.js
> +    ecmaVersion: 12,
Lo extraño es que realicé el pull y acepte todos los cambios, pero bueno ahora lo reviso

2022-01-27 01:16 UTC, AntonyFagundez approved these changes

2022-01-27 01:19 UTC, merged