General Refactor Cards Services Forms
alkemyTech/OT129-CLIENT pull request #94
Opened 2022-02-09 17:30 UTC by anagalli

## Principal refactors, adittions and changes: 

- Add contact form success alert (commit: https://github.com/alkemyTech/OT129-CLIENT/commit/4fdc3151430c1280451fc04284a8e0fdf2f6f262)
- Change SlidesContainer file from Components to Containers and update table styles (commit: https://github.com/alkemyTech/OT129-CLIENT/commit/0229619778032a83f422f3e62b721fa16cd6f062) 
- Refactor NewsIdPage with styles changes of its components (commit: https://github.com/alkemyTech/OT129-CLIENT/commit/628d73b5475f9fb70e802ccc084cd7fa56ae8074)
- Create ActivitiesIdPage to equal estructuration and styles of NewsIdPage (commit: https://github.com/alkemyTech/OT129-CLIENT/commit/d72b73fefd38d88af5441a956ca0eff508b03c3b)
- Remove HTML tags from cards (commit: https://github.com/alkemyTech/OT129-CLIENT/commit/5883fe24ab5415e7fab72dd820e1bee5a984af31)

**New visual for Activities and News detail:** 

![news detail](https://user-images.githubusercontent.com/97997049/153256194-52841416-fd53-4c72-bbdd-5d613d6257ed.JPG)

**Success alert in contact form:** 

![success contact form alert](https://user-images.githubusercontent.com/97997049/153255118-5241186a-d404-49c6-b8ba-96e0784b64e8.JPG)

2022-02-10 00:49 UTC, AntonyFagundez requested changes

2022-02-10 00:49 UTC, AntonyFagundez commented on src/Components/Contact/ContactForm.js
> +        response.status === 200 && alerts("Mensaje enviado correctamente.", "success");
Hola Ana como andas? axios por defecto considera como la promise resuelta en los [defaults](https://github.com/axios/axios#global-axios-defaults):
![Screenshot from 2022-02-09 21-45-41](https://user-images.githubusercontent.com/47680399/153315317-b42bb751-7e8c-456a-b1e8-f66693988d7f.png)

2022-02-10 00:49 UTC, AntonyFagundez commented on src/Components/Card/Card.js
> +        )}
Si description es null porque devuelve un p vacio?

Recordemos hacer uso y aprovecharnos de los valores falsys, (undefined, null, "", etc,) para mejorar legibilidad

2022-02-10 16:07 UTC, anagalli commented on src/Components/Contact/ContactForm.js
> +        response.status === 200 && alerts("Mensaje enviado correctamente.", "success");
Hola Antony! Ahí le saqué el condicional extra de que revise si el status de la respuesta es 200. No recordaba que tomaba esos valores por default.

2022-02-10 16:08 UTC, anagalli commented on src/Components/Card/Card.js
> +        )}
Acá tampoco recordé que null es falso por default. Cambié el if else, por un if que analiza description directamente como true o false.

2022-02-11 00:40 UTC, AntonyFagundez approved these changes

2022-02-11 00:41 UTC, merged